cacheFolder: ../.yarn/cache

checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

installStatePath: ../.yarn/integration-test-install-state.gz

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN-}"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
