name: pkg-pr-new Publish

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  prerelease:
    name: pkg-pr-new Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Prebuild libs
        run: yarn build:libs

      - name: Build and publish to pkg.pr.new
        run: yarn dlx pkg-pr-new publish --no-template packages/client-react-streaming packages/experimental-nextjs-app-support packages/nextjs packages/react-router packages/tanstack-start
