name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
      - run: yarn install --immutable --mode=skip-build
      - run: yarn workspace @apollo/experimental-nextjs-app-support run build
      - run: yarn workspace @apollo/experimental-nextjs-app-support exec npm publish --access public  --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
