name: "Run `size-limit`"
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - run: yarn install --immutable
      - uses: andresz1/size-limit-action@v1
        with:
          build_script: build:libs
          github_token: ${{ secrets.GITHUB_TOKEN }}
