name: Run tests
on:
  push:
    paths:
      - "package/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @apollo/experimental-nextjs-app-support test run
  tests_playwright:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Build
        run: yarn workspaces foreach -R -t --from integration-test run build
      - name: Run tests
        run: yarn workspace integration-test test
