name: Run tests
on:
  push:
    paths:
      - ".github/workflows/**"
      - "packages/**"
      - "integration-test/**"
      - "yarn.lock"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "packages/**"
      - "integration-test/**"
      - "yarn.lock"
  workflow_dispatch:
jobs:
  matrix:
    name: Determine if the `next` tag is higher than the `latest` tag
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - run: yarn install --immutable --mode=skip-build
      - name: Calculate Matrix
        id: version
        run: yarn matrix | tee $GITHUB_OUTPUT

  test:
    name: Unit Tests
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.matrix.outputs.version) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: "yarn"
      - name: Set target version of Apollo Client (Root)
        run: npm pkg set resolutions.@apollo/client=$(npm view @apollo/client@${{ matrix.version }} version)
      - run: yarn install --mode=skip-build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
      - run: yarn workspaces foreach --all --include "@apollo/*" run build
      - run: yarn workspaces foreach --all --include "@apollo/*" run test | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}
  packageShapes:
    name: Test Bundles
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.matrix.outputs.version) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Set target version of Apollo Client (Root)
        run: npm pkg set resolutions.@apollo/client=$(npm view @apollo/client@${{ matrix.version }} version)
      - run: yarn install --mode=skip-build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
      - run: yarn workspaces foreach --all -t --include "@apollo/*" run test-bundle | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}
  tests_playwright:
    name: Integration Tests
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.matrix.outputs.version) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Set target version of Apollo Client (Root)
        run: npm pkg set resolutions.@apollo/client=$(npm view @apollo/client@${{ matrix.version }} version)
      - run: yarn install --mode=skip-build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: "false"

      - run: yarn build:libs

      - name: Get installed Playwright version
        id: playwright-version
        run: yarn why @playwright/test --json | jq '.children|to_entries[0].value.locator' --raw-output | sed 's/^.*npm:/PLAYWRIGHT_VERSION=/' >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      - name: "Next.js: Build"
        run: yarn workspace @integration-test/nextjs run build
      # Upload webpack-stats.json to use on relative-ci.yaml workflow
      - name: Upload webpack stats artifact
        if: matrix.version == 'latest'
        uses: relative-ci/agent-upload-artifact-action@v2
        with:
          webpackStatsFile: ./integration-test/nextjs/webpack-stats.json

      - name: "Next.js: Test"
        run: yarn workspace @integration-test/nextjs run test --output /tmp/playwright-output | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}

      - name: "TanStack Start: Build"
        run: yarn workspace @integration-test/tanstack-start run build

      - name: "TanStack Start: Test"
        run: yarn workspace @integration-test/tanstack-start run test --output /tmp/playwright-output | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}

      - name: "React Router: Build"
        run: yarn workspace @integration-test/react-router run build

      - name: "React Router: Test"
        run: yarn workspace @integration-test/react-router run test --output /tmp/playwright-output | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}

      - name: "Vite Streaming: Build"
        run: yarn workspace @integration-test/vite-streaming run build
      - name: "Vite Streaming: Test"
        run: yarn workspace @integration-test/vite-streaming run test --output /tmp/playwright-output | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}

      - name: "Jest: Test"
        run: yarn workspace @integration-test/jest run test | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}

      - name: "Upload Playwright Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: playwright-output
          path: /tmp/playwright-output
